name: hydro
run-name: hydro
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hydro oj"
      - run: sudo snap install curl
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: LANG=zh . <(curl https://hydro.ac/setup.sh)
      - run: hydrooj cli user setSuperAdmin 2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ðŸ This job's status is ${{ job.status }}."
